### ISSUE TITLE
模型性能咨询

### ISSUE THREAD

**Issue by TiantianZhang** [YanYan0716/MPL#6]
您好!
感谢您提供的解决思路，现在已经将代码复现，在训练的过程中发现学习率一直较低，同时，acc在11%左右，数据集是40000训练加10000unlabel，不知是否之前有遇到同样的问题？或者是否有训练的结果供参考一下，万分感谢！

global: 54890,[epoch: 885/EPOCH:   20] 	[U:0.0000, L:2.3018, M:-0.2417][TLoss: 2.0601]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000436]
global: 54910,[epoch: 885/EPOCH:   20] 	[U:0.0000, L:2.3028, M:-1.2781][TLoss: 1.0247]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000436]
testing teacher model ... acc: 9.94
testing ... acc: 9.94
saving for TBacc 9.94, Tpath:/home/MPL/data/weight/T
saving for SBacc 9.94, Spath:/home/MPL/data/weight/S
global: 54934,[epoch: 886/EPOCH:   20] 	[U:0.0000, L:2.3029, M:0.5197][TLoss: 2.8225]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000437]
global: 54954,[epoch: 886/EPOCH:   20] 	[U:0.0000, L:2.3024, M:0.2478][TLoss: 2.5502]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000437]
global: 54978,[epoch: 887/EPOCH:   20] 	[U:0.0000, L:2.3019, M:0.7670][TLoss: 3.0690]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000437]
global: 54998,[epoch: 887/EPOCH:   20] 	[U:0.0000, L:2.3025, M:-0.1077][TLoss: 2.1948]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000437]
global: 55022,[epoch: 888/EPOCH:   20] 	[U:0.0000, L:2.3019, M:0.7783][TLoss: 3.0802]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000438]
global: 55042,[epoch: 888/EPOCH:   20] 	[U:0.0000, L:2.3026, M:-0.6857][TLoss: 1.6169]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000438]
global: 55066,[epoch: 889/EPOCH:   20] 	[U:0.0000, L:2.3012, M:0.2990][TLoss: 2.6002]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000438]
global: 55086,[epoch: 889/EPOCH:   20] 	[U:0.0000, L:2.3025, M:-0.0912][TLoss: 2.2113]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000439]
global: 55110,[epoch: 890/EPOCH:   20] 	[U:0.0000, L:2.3017, M:-0.1873][TLoss: 2.1144]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000439]
global: 55130,[epoch: 890/EPOCH:   20] 	[U:0.0000, L:2.3017, M:0.1638][TLoss: 2.4655]/[SLoss: 2.3028]	[TLR: 0.000499]/[SLR: 0.000439]

config.py

IMG_SIZE = 32
BATCH_SIZE = 32
_MAX_LEVEL = 10
CUTOUT_CONST = 40.
TRANSLATE_CONST = 100.
REPLACE_COLOR = [128, 128, 128]
LABEL_FILE_PATH = "/home//MPL/data/train_data/train_data.csv"  # kaggle
UNLABEL_FILE_PATH = "/home//MPL/data/unlabel_data/unlabel_data.csv"
AUGMENT_MAGNITUDE = 16
SHUFFLE_SIZE = BATCH_SIZE * 16
DATA_LEN = 4000  # 数据集的总长度
NUM_XLA_SHARDS = -1
BATCH_NORM_EPSILON = 1e-5
BATCH_NORM_DECAY = 0.999
DROPOUT_RATE = 0.
DROPOUT = 0.2
NUM_CLASSES = 10
NUM_CLASS = 10
LOG_EVERY = 20
SAVE_EVERY = 5
TEA_SAVE_PATH = '/home/MPL/data/weight/T'
STD_SAVE_PATH = '/home/MPL/data/weight/S'
MAX_EPOCHS = 19200
MAX_STEPS = MAX_EPOCHS * (int(DATA_LEN / BATCH_SIZE)-1)
UDA_WEIGHT = 8  # uda的权重
UDA_STEPS = 20000
TEST_EVERY = 2
GRAD_BOUND = 1e9
EMA = 0.995
TEA_CONTINUE = False
STD_CONTINUE = False
TEA_LOAD_PATH = '../input/weights/weights/T'
STD_LOAD_PATH = '../input/weights/weights/S'
CONTINUE_EPOCH = 885
TEST_FILE_PATH = '/home/MPL/data/test_data/test_data.csv'
TEST_MODEL_PATH = '/home/MPL/data/weight/S'
UDA_DATA = 7
LABEL_SMOOTHING = 0.15
UDA_TEMP = 0.7
UDA_THRESHOLD = 0.6
STUDENT_LR = 0.0005  # student
STUDENT_LR_WARMUP_STEPS = 40000
STUDENT_LR_WAIT_STEPS = 20000
TEACHER_LR = 0.0005  # teacher
TEACHER_LR_WARMUP_STEPS = 10000
TEACHER_NUM_WAIT_STEPS = 0
LR_DECAY_TYPE = 'cosine'  # constant, exponential, cosine
NUM_DECAY_STEPS = 3000
LR_DECAY_RATE = 0.97
OPTIM_TYPE = 'sgd'  # sgd, momentum, rmsprop
WEIGHT_DECAY = 5e-4
DTYPE = tf.float32

**Comment by YanYan0716** [comment]
我没有完全train完 ，收敛到60%就没再做，如果你直接用config里面的参数可能效果会不好，因为那都是我后期微调设置的，初始参数要调一调啊，emm~有时间我再跑一下吧
